[
  {
    "Site": "La Mariposa Health Center",
    "Area": "Westside",
    "Address": "1020 W. 11th Avenue",
    "Additional Notes": "Former location",
    "Category": "Neighborhood",
    "": "",
    "address_for_geocoding": "1020 W. 11th Avenue Denver, CO",
    "Latitude": 39.73348,
    "Longitude": -105.0004525
  },
  {
    "Site": "Twentieth Street Recreation Center",
    "Area": "Eastside",
    "Address": "1021 20th Street",
    "Additional Notes": "Close to Northside neighborhoods; Leagues and teams formed here",
    "Category": "Neighborhood",
    "": "",
    "address_for_geocoding": "1021 20th Street Denver, CO",
    "Latitude": 39.7512997,
    "Longitude": -104.9901132
  },
  {
    "Site": "Operation SER/ Jobs for Progress",
    "Area": "Westside",
    "Address": "1039 Inca Street",
    "Additional Notes": "",
    "Category": "Political",
    "": "",
    "address_for_geocoding": "1039 Inca Street Denver, CO",
    "Latitude": 39.7327139,
    "Longitude": -104.9978962
  },
  {
    "Site": "West Side Action Center",
    "Area": "Westside",
    "Address": "1042-1048 Santa Fe Drive",
    "Additional Notes": "Both former locations of center",
    "Category": "Political",
    "": "",
    "address_for_geocoding": "1042-1048 Santa Fe Drive Denver, CO",
    "Latitude": 39.733007,
    "Longitude": -104.99838
  },
  {
    "Site": "Zocalo Shopping Center",
    "Area": "Westside",
    "Address": "1050 W. Colfax Avenue",
    "Additional Notes": "",
    "Category": "Commercial",
    "": "",
    "address_for_geocoding": "1050 W. Colfax Avenue Denver, CO",
    "Latitude": 39.7396965,
    "Longitude": -105.0010915
  },
  {
    "Site": "Zocalo Shopping Center",
    "Area": "Westside",
    "Address": "1050 W. Colfax Avenue",
    "Additional Notes": "",
    "Category": "Political",
    "": "",
    "address_for_geocoding": "1050 W. Colfax Avenue Denver, CO",
    "Latitude": 39.7396965,
    "Longitude": -105.0010915
  },
  {
    "Site": "Sam Sandos Westside Family Health Center",
    "Area": "Westside",
    "Address": "1100 Federal Boulevard, Current Location",
    "Additional Notes": "Current location Former location (no longer exists)",
    "Category": "Neighborhood",
    "": "",
    "address_for_geocoding": "1100 Federal Boulevard Denver, CO",
    "Latitude": 39.7343218,
    "Longitude": -105.0242368
  },
  {
    "Site": "Sam Sandos Westside Family Health Center",
    "Area": "Westside",
    "Address": "1100 Federal Boulevard",
    "Additional Notes": "",
    "Category": "Political",
    "": "",
    "address_for_geocoding": "1100 Federal Boulevard Denver, CO",
    "Latitude": 39.7343218,
    "Longitude": -105.0242368
  },
  {
    "Site": "Sam Sandos Westside Family Health Center",
    "Area": "Westside",
    "Address": "1100 Federal Boulevard",
    "Additional Notes": "",
    "Category": "Arts",
    "": "",
    "address_for_geocoding": "1100 Federal Boulevard Denver, CO",
    "Latitude": 39.7343218,
    "Longitude": -105.0242368
  },
  {
    "Site": "West Side Action Center",
    "Area": "Westside",
    "Address": "1100 Santa Fe Drive",
    "Additional Notes": "Both former locations of center",
    "Category": "Political",
    "": "",
    "address_for_geocoding": "1100 Santa Fe Drive Denver, CO",
    "Latitude": 39.7338793,
    "Longitude": -104.9984668
  },
  {
    "Site": "Greenlee Elementary School",
    "Area": "Westside",
    "Address": "1150 Lipan Street",
    "Additional Notes": "Officially Eligible for the National Register – 2005",
    "Category": "Educational",
    "": "",
    "address_for_geocoding": "1150 Lipan Street Denver, CO",
    "Latitude": 39.7345198,
    "Longitude": -105.0012285
  },
  {
    "Site": "The Original Chubby’s",
    "Area": "Northside",
    "Address": "1231 W. 38th Avenue",
    "Additional Notes": "",
    "Category": "Commercial",
    "": "",
    "address_for_geocoding": "1231 W. 38th Avenue Denver, CO",
    "Latitude": 39.7697135,
    "Longitude": -105.001548
  },
  {
    "Site": "Mitchell Elementary School",
    "Area": "Eastside",
    "Address": "1350 E. 33rd Avenue",
    "Additional Notes": "",
    "Category": "Educational",
    "": "",
    "address_for_geocoding": "1350 E. 33rd Avenue Denver, CO",
    "Latitude": 39.7624516,
    "Longitude": -104.9717882
  },
  {
    "Site": "Plaza de Santa Fe",
    "Area": "Westside",
    "Address": "1355 Santa Fe Drive",
    "Additional Notes": "",
    "Category": "Commercial",
    "": "",
    "address_for_geocoding": "1355 Santa Fe Drive Denver, CO",
    "Latitude": 39.7375076,
    "Longitude": -104.9991743
  },
  {
    "Site": "Plaza de Santa Fe",
    "Area": "Westside",
    "Address": "1355 Santa Fe Drive",
    "Additional Notes": "",
    "Category": "Political",
    "": "",
    "address_for_geocoding": "1355 Santa Fe Drive Denver, CO",
    "Latitude": 39.7375076,
    "Longitude": -104.9991743
  },
  {
    "Site": "El Centro de las Familias Mental Health Center",
    "Area": "Westside",
    "Address": "1405 Federal Boulevard",
    "Additional Notes": "Current location",
    "Category": "Neighborhood",
    "": "",
    "address_for_geocoding": "1405 Federal Boulevard Denver, CO",
    "Latitude": 39.7382243,
    "Longitude": -105.0256977
  },
  {
    "Site": "GAO Homes",
    "Area": "Westside",
    "Address": "1409 Julian Street",
    "Additional Notes": "",
    "Category": "Political",
    "": "",
    "address_for_geocoding": "1409 Julian Street Denver, CO",
    "Latitude": 39.7387718,
    "Longitude": -105.0313036
  },
  {
    "Site": "GAO Homes",
    "Area": "Westside",
    "Address": "1445 Knox Court, 1409 Julian Street",
    "Additional Notes": "",
    "Category": "Political",
    "": "",
    "address_for_geocoding": "1445 Knox Court Denver, CO",
    "Latitude": 39.7393391,
    "Longitude": -105.0326146
  },
  {
    "Site": "La Raza (formerly Columbus) Park",
    "Area": "Northside",
    "Address": "1501 W. 38th Avenue",
    "Additional Notes": "",
    "Category": "Chicano Movement or Crusade for Justice",
    "": "",
    "address_for_geocoding": "1501 W. 38th Avenue Denver, CO",
    "Latitude": 39.7703352,
    "Longitude": -105.0044467
  },
  {
    "Site": "La Raza (formerly Columbus) Park",
    "Area": "Northside",
    "Address": "1501 W. 38th Avenue",
    "Additional Notes": "Chicano Movement, activism",
    "Category": "Neighborhood",
    "": "",
    "address_for_geocoding": "1501 W. 38th Avenue Denver, CO",
    "Latitude": 39.7703352,
    "Longitude": -105.0044467
  },
  {
    "Site": "Cheltenham Elementary",
    "Area": "Northside",
    "Address": "1580 Julian Street",
    "Additional Notes": "",
    "Category": "Educational",
    "": "",
    "address_for_geocoding": "1580 Julian Street Denver, CO",
    "Latitude": 39.7419111,
    "Longitude": -105.0311764
  },
  {
    "Site": "Gang Rescue and Support Project (GRASP)",
    "Area": "Eastside",
    "Address": "1625 W. 35th Avenue",
    "Additional Notes": "Tramway Nonprofit Center (former tramway building)",
    "Category": "Neighborhood",
    "": "",
    "address_for_geocoding": "1625 W. 35th Avenue Denver, CO",
    "Latitude": 39.7656434,
    "Longitude": -105.0058648
  },
  {
    "Site": "Manual High School",
    "Area": "Eastside",
    "Address": "1700 E. 28th Avenue",
    "Additional Notes": "",
    "Category": "Educational",
    "": "",
    "address_for_geocoding": "1700 E. 28th Avenue Denver, CO",
    "Latitude": 39.7563751,
    "Longitude": -104.9680001
  },
  {
    "Site": "Sloan’s Lake Park",
    "Area": "Northside",
    "Address": "1700 N. Sheridan Boulevard",
    "Additional Notes": "Boxing fights held in building located at W.17th Avenue and Sheridan Boulevard",
    "Category": "Neighborhood",
    "": "",
    "address_for_geocoding": "1700 N. Sheridan Boulevard Denver, CO",
    "Latitude": 39.744609,
    "Longitude": -105.0528756
  },
  {
    "Site": "GI Forum",
    "Area": "Westside",
    "Address": "1717 Federal Boulevard",
    "Additional Notes": "",
    "Category": "Labor-related",
    "": "",
    "address_for_geocoding": "1717 Federal Boulevard Denver, CO",
    "Latitude": 39.7443999,
    "Longitude": -105.0257434
  },
  {
    "Site": "GI Forum",
    "Area": "Westside",
    "Address": "1717 Federal Boulevard",
    "Additional Notes": "",
    "Category": "Political",
    "": "",
    "address_for_geocoding": "1717 Federal Boulevard Denver, CO",
    "Latitude": 39.7443999,
    "Longitude": -105.0257434
  },
  {
    "Site": "Grupo Folklórico Sabor Latino",
    "Area": "Northside",
    "Address": "1815 W. 34th Avenue",
    "Additional Notes": "",
    "Category": "Arts",
    "": "",
    "address_for_geocoding": "1815 W. 34th Avenue Denver, CO",
    "Latitude": 39.7647344,
    "Longitude": -105.0084182
  },
  {
    "Site": "Denison Montessori",
    "Area": "Southwest",
    "Address": "1821 S. Yates Street",
    "Additional Notes": "",
    "Category": "Educational",
    "": "",
    "address_for_geocoding": "1821 S. Yates Street Denver, CO",
    "Latitude": 39.6827115,
    "Longitude": -105.0517231
  },
  {
    "Site": "El Chapultepec",
    "Area": "Eastside",
    "Address": "1962 Market Street",
    "Additional Notes": "Closed in 2021",
    "Category": "Commercial",
    "": "",
    "address_for_geocoding": "1962 Market Street Denver, CO",
    "Latitude": 39.7533561,
    "Longitude": -104.9934913
  },
  {
    "Site": "El Chapultepec",
    "Area": "Eastside",
    "Address": "1962 Market Street",
    "Additional Notes": "",
    "Category": "Arts",
    "": "",
    "address_for_geocoding": "1962 Market Street Denver, CO",
    "Latitude": 39.7533561,
    "Longitude": -104.9934913
  },
  {
    "Site": "La Casa de Manuel",
    "Area": "Eastside",
    "Address": "2010 Larimer Street (original location) (no longer exists)",
    "Additional Notes": "",
    "Category": "Commercial",
    "": "",
    "address_for_geocoding": "2010 Larimer Street Denver, CO",
    "Latitude": 39.7530131,
    "Longitude": -104.9921068
  },
  {
    "Site": "Johnnie’s Market",
    "Area": "Eastside",
    "Address": "2030 Larimer Street",
    "Additional Notes": "",
    "Category": "Commercial",
    "": "",
    "address_for_geocoding": "2030 Larimer Street Denver, CO",
    "Latitude": 39.7532573,
    "Longitude": -104.9918544
  },
  {
    "Site": "La Popular Food Company",
    "Area": "Eastside",
    "Address": "2033 Lawrence Street",
    "Additional Notes": "",
    "Category": "Commercial",
    "": "",
    "address_for_geocoding": "2033 Lawrence Street Denver, CO",
    "Latitude": 39.7529299,
    "Longitude": -104.991346
  },
  {
    "Site": "Los Compadres",
    "Area": "Eastside",
    "Address": "2034 Larimer Street",
    "Additional Notes": "",
    "Category": "Commercial",
    "": "",
    "address_for_geocoding": "2034 Larimer Street Denver, CO",
    "Latitude": 39.7532976,
    "Longitude": -104.9917682
  },
  {
    "Site": "Mexico City",
    "Area": "Eastside",
    "Address": "2115 Larimer Street",
    "Additional Notes": "",
    "Category": "Commercial",
    "": "",
    "address_for_geocoding": "2115 Larimer Street Denver, CO",
    "Latitude": 39.7543139,
    "Longitude": -104.9913003
  },
  {
    "Site": "Sam’s Kustom Hydraulics",
    "Area": "Southwest",
    "Address": "2165 W. Evans Avenue",
    "Additional Notes": "",
    "Category": "Neighborhood",
    "": "",
    "address_for_geocoding": "2165 W. Evans Avenue Denver, CO",
    "Latitude": 39.6790076,
    "Longitude": -105.0125953
  },
  {
    "Site": "KFSC Radio",
    "Area": "Eastside",
    "Address": "2185 Broadway, second location",
    "Additional Notes": "",
    "Category": "Commercial",
    "": "",
    "address_for_geocoding": "2185 Broadway Denver, CO",
    "Latitude": 39.7525179,
    "Longitude": -104.9876261
  },
  {
    "Site": "Grandpa’s Burger Haven",
    "Area": "Westside",
    "Address": "23 S. Federal Boulevard",
    "Additional Notes": "Lowrider events",
    "Category": "Neighborhood",
    "": "",
    "address_for_geocoding": "23 S. Federal Boulevard Denver, CO",
    "Latitude": 39.7159016,
    "Longitude": -105.0254923
  },
  {
    "Site": "Rodolfo and Geraldine Gonzales Residence",
    "Area": "Eastside",
    "Address": "2385 Leyden Street",
    "Additional Notes": "Not shown within map boundaries",
    "Category": "Chicano Movement or Crusade for Justice",
    "": "",
    "address_for_geocoding": "2385 Leyden Street Denver, CO",
    "Latitude": 39.7525271,
    "Longitude": -104.9155471
  },
  {
    "Site": "Panaderia Rosales",
    "Area": "Northside",
    "Address": "2636 W. 32nd Avenue",
    "Additional Notes": "",
    "Category": "Commercial",
    "": "",
    "address_for_geocoding": "2636 W. 32nd Avenue Denver, CO",
    "Latitude": 39.7618252,
    "Longitude": -105.0199714
  },
  {
    "Site": "Holiday Theater",
    "Area": "Northside",
    "Address": "2644 W. 32nd Avenue",
    "Additional Notes": "",
    "Category": "Commercial",
    "": "",
    "address_for_geocoding": "2644 W. 32nd Avenue Denver, CO",
    "Latitude": 39.7618863,
    "Longitude": -105.0202467
  },
  {
    "Site": "Holiday Theater",
    "Area": "Northside",
    "Address": "2644 W. 32nd Avenue",
    "Additional Notes": "",
    "Category": "Arts",
    "": "",
    "address_for_geocoding": "2644 W. 32nd Avenue Denver, CO",
    "Latitude": 39.7618863,
    "Longitude": -105.0202467
  },
  {
    "Site": "Our Lady of Grace",
    "Area": "Eastside",
    "Address": "2645 E. 48th Avenue",
    "Additional Notes": "",
    "Category": "Religious",
    "": "",
    "address_for_geocoding": "2645 E. 48th Avenue Denver, CO",
    "Latitude": 39.7840429,
    "Longitude": -104.95545
  },
  {
    "Site": "Columbian Elementary School",
    "Area": "Northside",
    "Address": "2925 W. 40th Street",
    "Additional Notes": "Field Eligible – 1983",
    "Category": "Educational",
    "": "",
    "address_for_geocoding": "2925 W. 40th Street Denver, CO",
    "Latitude": 39.7726517,
    "Longitude": -105.0235147
  },
  {
    "Site": "St. Cajetan Catholic Parish",
    "Area": "Westside",
    "Address": "299 S. Raleigh Street",
    "Additional Notes": "Current Location",
    "Category": "Religious",
    "": "",
    "address_for_geocoding": "299 S. Raleigh Street Denver, CO",
    "Latitude": 39.7115369,
    "Longitude": -105.0427606
  },
  {
    "Site": "St. Cajetan Catholic Parish",
    "Area": "Westside",
    "Address": "299 South Raleigh Street",
    "Additional Notes": "",
    "Category": "Arts",
    "": "",
    "address_for_geocoding": "299 South Raleigh Street Denver, CO",
    "Latitude": 39.7115369,
    "Longitude": -105.0427606
  },
  {
    "Site": "Columbine Steak House",
    "Area": "Westside",
    "Address": "300 Federal Boulevard",
    "Additional Notes": "Lowrider events",
    "Category": "Neighborhood",
    "": "",
    "address_for_geocoding": "300 Federal Boulevard Denver, CO",
    "Latitude": 39.7213094,
    "Longitude": -105.0248074
  },
  {
    "Site": "Rodolfo and Geraldine Gonzales Residence",
    "Area": "Eastside",
    "Address": "3050 Vine Street 2385 Leyden Street",
    "Additional Notes": "Not shown within map boundaries",
    "Category": "Chicano Movement or Crusade for Justice",
    "": "",
    "address_for_geocoding": "3050 Vine Street 2385 Leyden Street Denver, CO",
    "Latitude": 39.7604752,
    "Longitude": -104.9619244
  },
  {
    "Site": "La Casa de Manuel",
    "Area": "Eastside",
    "Address": "3158 Larimer Street, Current Location",
    "Additional Notes": "",
    "Category": "Commercial",
    "": "",
    "address_for_geocoding": "3158 Larimer Street Denver, CO",
    "Latitude": 39.7636979,
    "Longitude": -104.9780894
  },
  {
    "Site": "Tejon Drugs",
    "Area": "Northside",
    "Address": "3158 Tejon Street",
    "Additional Notes": "",
    "Category": "Commercial",
    "": "",
    "address_for_geocoding": "3158 Tejon Street Denver, CO",
    "Latitude": 39.7618608,
    "Longitude": -105.0110356
  },
  {
    "Site": "KFSC Radio",
    "Area": "Eastside",
    "Address": "3340 Lafayette Street, original location",
    "Additional Notes": "",
    "Category": "Commercial",
    "": "",
    "address_for_geocoding": "3340 Lafayette Street Denver, CO",
    "Latitude": 39.7640869,
    "Longitude": -104.9705787
  },
  {
    "Site": "Chávez (César E.) Park",
    "Area": "Northside Westside",
    "Address": "3401 Pecos Street",
    "Additional Notes": "Chicano Movement, activism current location?",
    "Category": "Neighborhood",
    "": "",
    "address_for_geocoding": "3401 Pecos Street  Denver, CO",
    "Latitude": 39.7647889,
    "Longitude": -105.0066607
  },
  {
    "Site": "Saint Patrick’s School/ Escuela Guadalupe/Call for Action Center/Chicano Humanities & Arts Council (CHAC)",
    "Area": "Northside",
    "Address": "3401 Pecos Street",
    "Additional Notes": "",
    "Category": "Educational",
    "": "",
    "address_for_geocoding": "3401 Pecos Street Denver, CO",
    "Latitude": 39.7647889,
    "Longitude": -105.0066607
  },
  {
    "Site": "Call for Action Center/ Chicano Humanities & Arts Council (CHAC)/Saint Patrick’s School",
    "Area": "Northside",
    "Address": "3401 Pecos Street",
    "Additional Notes": "",
    "Category": "Arts",
    "": "",
    "address_for_geocoding": "3401 Pecos Street Denver, CO",
    "Latitude": 39.7647889,
    "Longitude": -105.0066607
  },
  {
    "Site": "Mi Casa Resource Center",
    "Area": "Westside",
    "Address": "345 S. Grove Street",
    "Additional Notes": "Current Location; Includes Salazar Center for Family Prosperity",
    "Category": "Chicano Movement or Crusade for Justice",
    "": "",
    "address_for_geocoding": "345 S. Grove Street Denver, CO",
    "Latitude": 39.710451,
    "Longitude": -105.0265994
  },
  {
    "Site": "Annunciation Catholic School",
    "Area": "Eastside",
    "Address": "3536 Lafayette Street",
    "Additional Notes": "",
    "Category": "Educational",
    "": "",
    "address_for_geocoding": "3536 Lafayette Street Denver, CO",
    "Latitude": 39.7662413,
    "Longitude": -104.9705103
  },
  {
    "Site": "Annunciation Catholic School",
    "Area": "Eastside",
    "Address": "3546 Lafayette Street",
    "Additional Notes": "",
    "Category": "Religious",
    "": "",
    "address_for_geocoding": "3546 Lafayette Street Denver, CO",
    "Latitude": 39.7665549,
    "Longitude": -104.9705546
  },
  {
    "Site": "Tamales by La Casita",
    "Area": "Northside",
    "Address": "3561 Tejon Street",
    "Additional Notes": "",
    "Category": "Commercial",
    "": "",
    "address_for_geocoding": "3561 Tejon Street Denver, CO",
    "Latitude": 39.7664218,
    "Longitude": -105.0115909
  },
  {
    "Site": "Tamales by La Casita",
    "Area": "Northside",
    "Address": "3561 Tejon Street",
    "Additional Notes": "2005 building extant",
    "Category": "Political",
    "": "",
    "address_for_geocoding": "3561 Tejon Street Denver, CO",
    "Latitude": 39.7664218,
    "Longitude": -105.0115909
  },
  {
    "Site": "Ross-Barnum Branch Library",
    "Area": "Westside",
    "Address": "3570 W. 1st Avenue",
    "Additional Notes": "Officially Eligible for the National Register– 2014",
    "Category": "Neighborhood",
    "": "",
    "address_for_geocoding": "3570 W. 1st Avenue Denver, CO",
    "Latitude": 39.7179491,
    "Longitude": -105.0346007
  },
  {
    "Site": "Garfield Lake Park",
    "Area": "Southwest",
    "Address": "3600 W. Mississippi Avenue",
    "Additional Notes": "",
    "Category": "Neighborhood",
    "": "",
    "address_for_geocoding": "3600 W. Mississippi Avenue Denver, CO",
    "Latitude": 39.6958195,
    "Longitude": -105.0360161
  },
  {
    "Site": "La Luz Del Mundo Iglesia Del Dios Vivo Columna Y Apoyo De La Verdad",
    "Area": "Westside",
    "Address": "3607 W. 14th Avenue",
    "Additional Notes": "",
    "Category": "Religious",
    "": "",
    "address_for_geocoding": "3607 W. 14th Avenue Denver, CO",
    "Latitude": 39.7386773,
    "Longitude": -105.0349431
  },
  {
    "Site": "Papa Rocks/Lechuga’s",
    "Area": "Northside",
    "Address": "3609 Tejon Street",
    "Additional Notes": "",
    "Category": "Commercial",
    "": "",
    "address_for_geocoding": "3609 Tejon Street Denver, CO",
    "Latitude": 39.7670757,
    "Longitude": -105.0114083
  },
  {
    "Site": "Papa Rocks/Lechuga’s",
    "Area": "Northside",
    "Address": "3609 Tejon Street",
    "Additional Notes": "",
    "Category": "Political",
    "": "",
    "address_for_geocoding": "3609 Tejon Street Denver, CO",
    "Latitude": 39.7670757,
    "Longitude": -105.0114083
  },
  {
    "Site": "Pirate: A Contemporary Art Oasis",
    "Area": "Northside",
    "Address": "3655 Navajo Street",
    "Additional Notes": "Former Location",
    "Category": "Arts",
    "": "",
    "address_for_geocoding": "3655 Navajo Street Denver, CO",
    "Latitude": 39.7678616,
    "Longitude": -105.0044011
  },
  {
    "Site": "Pirate: A Contemporary Art Oasis",
    "Area": "Northside",
    "Address": "3655 Navajo Street",
    "Additional Notes": "Former Location",
    "Category": "Neighborhood",
    "": "",
    "address_for_geocoding": "3655 Navajo Street Denver, CO",
    "Latitude": 39.7678616,
    "Longitude": -105.0044011
  },
  {
    "Site": "La Academia Sandoval (Sandoval Elementary)",
    "Area": "Northside",
    "Address": "3655 Wyandot Street",
    "Additional Notes": "",
    "Category": "Educational",
    "": "",
    "address_for_geocoding": "3655 Wyandot Street Denver, CO",
    "Latitude": 39.7677841,
    "Longitude": -105.0152887
  },
  {
    "Site": "Barnum Park",
    "Area": "Westside",
    "Address": "370 Hooker Street",
    "Additional Notes": "",
    "Category": "Neighborhood",
    "": "",
    "address_for_geocoding": "370 Hooker Street Denver, CO",
    "Latitude": 39.7227185,
    "Longitude": -105.0280832
  },
  {
    "Site": "SPMDTU Meeting Hall",
    "Area": "Northside",
    "Address": "3758 Osage Street",
    "Additional Notes": "Location needs to be confirmed",
    "Category": "Labor-related",
    "": "",
    "address_for_geocoding": "3758 Osage Street Denver, CO",
    "Latitude": 39.7689651,
    "Longitude": -105.0048349
  },
  {
    "Site": "St. Charles Recreation Center",
    "Area": "Eastside",
    "Address": "3777 Lafayette Street",
    "Additional Notes": "On land of former boyhood home of Rodolfo “Corky” Gonzales",
    "Category": "Chicano Movement or Crusade for Justice",
    "": "",
    "address_for_geocoding": "3777 Lafayette Street Denver, CO",
    "Latitude": 39.769361,
    "Longitude": -104.9713318
  },
  {
    "Site": "St. Anthony of Padua",
    "Area": "Southwest",
    "Address": "3801 W. Ohio Avenue",
    "Additional Notes": "",
    "Category": "Religious",
    "": "",
    "address_for_geocoding": "3801 W. Ohio Avenue Denver, CO",
    "Latitude": 39.7027426,
    "Longitude": -105.0372945
  },
  {
    "Site": "St. Anthony of Padua",
    "Area": "Southwest",
    "Address": "3801 W. Ohio Avenue",
    "Additional Notes": "",
    "Category": "Neighborhood",
    "": "",
    "address_for_geocoding": "3801 W. Ohio Avenue Denver, CO",
    "Latitude": 39.7027426,
    "Longitude": -105.0372945
  },
  {
    "Site": "Troy Chavez Memorial Peace Garden",
    "Area": "Northside",
    "Address": "3825 Shoshone Street",
    "Additional Notes": "",
    "Category": "Arts",
    "": "",
    "address_for_geocoding": "3825 Shoshone Street Denver, CO",
    "Latitude": 39.7698562,
    "Longitude": -105.0100959
  },
  {
    "Site": "Troy Chavez Memorial Peace Garden",
    "Area": "Northside",
    "Address": "3825 Shoshone Street",
    "Additional Notes": "",
    "Category": "Neighborhood",
    "": "",
    "address_for_geocoding": "3825 Shoshone Street Denver, CO",
    "Latitude": 39.7698562,
    "Longitude": -105.0100959
  },
  {
    "Site": "Servicios de la Raza",
    "Area": "Northside",
    "Address": "4051 Tejon Street",
    "Additional Notes": "Former location",
    "Category": "Chicano Movement or Crusade for Justice",
    "": "",
    "address_for_geocoding": "4051 Tejon Street Denver, CO",
    "Latitude": 39.772731,
    "Longitude": -105.0114996
  },
  {
    "Site": "Chávez (César E.) Park",
    "Area": "Northside Westside",
    "Address": "4134 N. Tennyson Street",
    "Additional Notes": "Chicano Movement, activism Original Location",
    "Category": "Neighborhood",
    "": "",
    "address_for_geocoding": "4134 N. Tennyson Street Denver, CO",
    "Latitude": 39.7729812,
    "Longitude": -105.0437464
  },
  {
    "Site": "Chavez (Cesar E.) Park",
    "Area": "Northside",
    "Address": "4134 N. Tennyson Street",
    "Additional Notes": "",
    "Category": "Chicano Movement or Crusade for Justice",
    "": "",
    "address_for_geocoding": "4134 N. Tennyson Street Denver, CO",
    "Latitude": 39.7729812,
    "Longitude": -105.0437464
  },
  {
    "Site": "St. Catherine of Siena",
    "Area": "",
    "Address": "4200 Federal Boulevard",
    "Additional Notes": "Officially Eligible for the National Register – 2001",
    "Category": "Religious",
    "": "",
    "address_for_geocoding": "4200 Federal Boulevard Denver, CO",
    "Latitude": 39.7743748,
    "Longitude": -105.0247304
  },
  {
    "Site": "Holy Family Church",
    "Area": "Northside",
    "Address": "4377 Utica Street",
    "Additional Notes": "",
    "Category": "Religious",
    "": "",
    "address_for_geocoding": "4377 Utica Street Denver, CO",
    "Latitude": 39.7761173,
    "Longitude": -105.0454675
  },
  {
    "Site": "Aztlán Recreation Center",
    "Area": "Northside",
    "Address": "4435 Navajo Street",
    "Additional Notes": "",
    "Category": "Neighborhood",
    "": "",
    "address_for_geocoding": "4435 Navajo Street Denver, CO",
    "Latitude": 39.7775478,
    "Longitude": -105.0045152
  },
  {
    "Site": "St. Jacob’s Lodge Hall",
    "Area": "Northside",
    "Address": "4483 Logan Street",
    "Additional Notes": "",
    "Category": "Labor-related",
    "": "",
    "address_for_geocoding": "4483 Logan Street Denver, CO",
    "Latitude": 39.778064,
    "Longitude": -104.9825518
  },
  {
    "Site": "Juanita Nolasco Residences",
    "Area": "Westside",
    "Address": "4550 W. 9th Avenue",
    "Additional Notes": "",
    "Category": "Political",
    "": "",
    "address_for_geocoding": "4550 W. 9th Avenue Denver, CO",
    "Latitude": 39.7309297,
    "Longitude": -105.0459013
  },
  {
    "Site": "Denver Coliseum",
    "Area": "Eastside",
    "Address": "4600 Humboldt Street",
    "Additional Notes": "Boxing",
    "Category": "Neighborhood",
    "": "",
    "address_for_geocoding": "4600 Humboldt Street Denver, CO",
    "Latitude": 39.779002,
    "Longitude": -104.9702685
  },
  {
    "Site": "Lakeside Amusement Park",
    "Area": "Northside",
    "Address": "4601 Sheridan Boulevard",
    "Additional Notes": "",
    "Category": "Neighborhood",
    "": "",
    "address_for_geocoding": "4601 Sheridan Boulevard Denver, CO",
    "Latitude": 39.7785794,
    "Longitude": -105.0534811
  },
  {
    "Site": "Berkeley Lake Park",
    "Area": "Northside",
    "Address": "4601 W. 46th Avenue",
    "Additional Notes": "",
    "Category": "Neighborhood",
    "": "",
    "address_for_geocoding": "4601 W. 46th Avenue Denver, CO",
    "Latitude": 39.7813028,
    "Longitude": -105.047859
  },
  {
    "Site": "Valdez-Perry Branch Library",
    "Area": "Eastside",
    "Address": "4690 Vine Street",
    "Additional Notes": "",
    "Category": "Political",
    "": "",
    "address_for_geocoding": "4690 Vine Street Denver, CO",
    "Latitude": 39.781672,
    "Longitude": -104.9621129
  },
  {
    "Site": "Good Americans Organization (GAO) Hall",
    "Area": "Northside",
    "Address": "4700 Lipan Street",
    "Additional Notes": "",
    "Category": "Political",
    "": "",
    "address_for_geocoding": "4700 Lipan Street Denver, CO",
    "Latitude": 39.7822763,
    "Longitude": -105.0011828
  },
  {
    "Site": "MGM’s Nightclub",
    "Area": "Southwest",
    "Address": "4801 Morrison Road",
    "Additional Notes": "",
    "Category": "Commercial",
    "": "",
    "address_for_geocoding": "4801 Morrison Road Denver, CO",
    "Latitude": 39.7001878,
    "Longitude": -105.0487323
  },
  {
    "Site": "MGM’s Nightclub",
    "Area": "Southwest",
    "Address": "4801 Morrison Road",
    "Additional Notes": "",
    "Category": "Political",
    "": "",
    "address_for_geocoding": "4801 Morrison Road Denver, CO",
    "Latitude": 39.7001878,
    "Longitude": -105.0487323
  },
  {
    "Site": "Emmanuel’s Bakery",
    "Area": "Northside",
    "Address": "500 E. 45th Avenue",
    "Additional Notes": "",
    "Category": "Commercial",
    "": "",
    "address_for_geocoding": "500 E. 45th Avenue Denver, CO",
    "Latitude": 39.7781689,
    "Longitude": -104.9811218
  },
  {
    "Site": "Knapp Elementary School",
    "Area": "Southwest",
    "Address": "500 S Utica Street",
    "Additional Notes": "Field Not Eligible for the National Register – 2001",
    "Category": "Educational",
    "": "",
    "address_for_geocoding": "500 S Utica Street Denver, CO",
    "Latitude": 39.7077977,
    "Longitude": -105.0448054
  },
  {
    "Site": "Mr. James Beauty Salon",
    "Area": "Northside",
    "Address": "5038 Federal Boulevard",
    "Additional Notes": "",
    "Category": "Commercial",
    "": "",
    "address_for_geocoding": "5038 Federal Boulevard Denver, CO",
    "Latitude": 39.7881448,
    "Longitude": -105.024933
  },
  {
    "Site": "Lucia Lucero residence",
    "Area": "Westside",
    "Address": "547 Galapago Street",
    "Additional Notes": "Mrs. Lucero helped provide shelter to young LGBTQ Latinos",
    "Category": "Neighborhood",
    "": "",
    "address_for_geocoding": "547 Galapago Street Denver, CO",
    "Latitude": 39.7250219,
    "Longitude": -104.9966409
  },
  {
    "Site": "La Familia Recreation Center",
    "Area": "Westside",
    "Address": "55 S. Elati Street",
    "Additional Notes": "",
    "Category": "Political",
    "": "",
    "address_for_geocoding": "55 S. Elati Street Denver, CO",
    "Latitude": 39.7157063,
    "Longitude": -104.9941853
  },
  {
    "Site": "Mi Casa Resource Center",
    "Area": "Westside",
    "Address": "571 Galapago Street",
    "Additional Notes": "Original Location",
    "Category": "Chicano Movement or Crusade for Justice",
    "": "",
    "address_for_geocoding": "571 Galapago Street Denver, CO",
    "Latitude": 39.7253991,
    "Longitude": -104.9966181
  },
  {
    "Site": "Flores (Hector M.) Park",
    "Area": "Westside",
    "Address": "621 W. 4th Avenue",
    "Additional Notes": "Mini (pocket) park",
    "Category": "Neighborhood",
    "": "",
    "address_for_geocoding": "621 W. 4th Avenue Denver, CO",
    "Latitude": 39.7228716,
    "Longitude": -104.9960703
  },
  {
    "Site": "Holy Ghost Church",
    "Area": "Eastside",
    "Address": "633 19th Street",
    "Additional Notes": "",
    "Category": "Religious",
    "": "",
    "address_for_geocoding": "633 19th Street Denver, CO",
    "Latitude": 39.7477707,
    "Longitude": -104.9878043
  },
  {
    "Site": "Lincoln Elementary and Montessori School",
    "Area": "South Denver",
    "Address": "710 S. Pennsylvania Street",
    "Additional Notes": "",
    "Category": "Educational",
    "": "",
    "address_for_geocoding": "710 S. Pennsylvania Street Denver, CO",
    "Latitude": 39.703568,
    "Longitude": -104.981099
  },
  {
    "Site": "8th Avenue Barbershop",
    "Area": "Westside",
    "Address": "715 W. 8th Avenue",
    "Additional Notes": "",
    "Category": "Commercial",
    "": "",
    "address_for_geocoding": "715 W. 8th Avenue Denver, CO",
    "Latitude": 39.7290301,
    "Longitude": -104.9968088
  },
  {
    "Site": "Su Teatro Cultural and Performing Arts Center/ Denver Civic Theatre",
    "Area": "Westside",
    "Address": "721 Santa Fe Drive",
    "Additional Notes": "",
    "Category": "Arts",
    "": "",
    "address_for_geocoding": "721 Santa Fe Drive Denver, CO",
    "Latitude": 39.7277691,
    "Longitude": -104.9988656
  },
  {
    "Site": "El Noa Noa",
    "Area": "Westside",
    "Address": "722 Santa Fe Drive",
    "Additional Notes": "",
    "Category": "Commercial",
    "": "",
    "address_for_geocoding": "722 Santa Fe Drive Denver, CO",
    "Latitude": 39.7277702,
    "Longitude": -104.9983527
  },
  {
    "Site": "El Centro de las Familias Mental Health Center",
    "Area": "Westside",
    "Address": "75 Meade Street",
    "Additional Notes": "Original location – slated to be demolished",
    "Category": "Neighborhood",
    "": "",
    "address_for_geocoding": "75 Meade Street Denver, CO",
    "Latitude": 39.7179443,
    "Longitude": -105.036427
  },
  {
    "Site": "Del Pueblo/Girls Athletic Leadership Schools",
    "Area": "West Side",
    "Address": "750 Galapago Street",
    "Additional Notes": "",
    "Category": "Educational",
    "": "",
    "address_for_geocoding": "750 Galapago Street Denver, CO",
    "Latitude": 39.7286008,
    "Longitude": -104.9959334
  },
  {
    "Site": "Joe’s Buffet",
    "Area": "Westside",
    "Address": "753 Santa Fe Drive",
    "Additional Notes": "",
    "Category": "Commercial",
    "": "",
    "address_for_geocoding": "753 Santa Fe Drive Denver, CO",
    "Latitude": 39.728325,
    "Longitude": -104.999052
  },
  {
    "Site": "Casita Esperanza Health Station",
    "Area": "Westside",
    "Address": "801 W. 5th Avenue",
    "Additional Notes": "Closed in 1979",
    "Category": "Neighborhood",
    "": "",
    "address_for_geocoding": "801 W. 5th Avenue Denver, CO",
    "Latitude": 39.7242975,
    "Longitude": -104.9978049
  },
  {
    "Site": "Jiggs Barbershop",
    "Area": "Westside",
    "Address": "836 Santa Fe Drive",
    "Additional Notes": "",
    "Category": "Commercial",
    "": "",
    "address_for_geocoding": "836 Santa Fe Drive Denver, CO",
    "Latitude": 39.7296487,
    "Longitude": -104.998444
  },
  {
    "Site": "Congress Park",
    "Area": "In Denver, outside of map boundaries",
    "Address": "850 N. Josephine Street",
    "Additional Notes": "",
    "Category": "Neighborhood",
    "": "",
    "address_for_geocoding": "850 N. Josephine Street Denver, CO",
    "Latitude": 39.7301819,
    "Longitude": -104.9589019
  },
  {
    "Site": "Museo de las Americas",
    "Area": "Westside",
    "Address": "861 Santa Fe Drive",
    "Additional Notes": "",
    "Category": "Arts",
    "": "",
    "address_for_geocoding": "861 Santa Fe Drive Denver, CO",
    "Latitude": 39.7300491,
    "Longitude": -104.9989918
  },
  {
    "Site": "West Side Coalition Office",
    "Area": "Westside",
    "Address": "877 Santa Fe Drive",
    "Additional Notes": "",
    "Category": "Political",
    "": "",
    "address_for_geocoding": "877 Santa Fe Drive Denver, CO",
    "Latitude": 39.7303655,
    "Longitude": -104.998832
  },
  {
    "Site": "Auraria Higher Education Center",
    "Area": "Westside",
    "Address": "890 Auraria Parkway",
    "Additional Notes": "",
    "Category": "Educational",
    "": "",
    "address_for_geocoding": "890 Auraria Parkway Denver, CO",
    "Latitude": 39.7453106,
    "Longitude": -105.0076422
  },
  {
    "Site": "Metropolitan State University of Denver",
    "Area": "Westside",
    "Address": "890 Auraria Parkway",
    "Additional Notes": "",
    "Category": "Arts",
    "": "",
    "address_for_geocoding": "890 Auraria Parkway Denver, CO",
    "Latitude": 39.7453106,
    "Longitude": -105.0076422
  },
  {
    "Site": "Kepner Middle School",
    "Area": "Southwest",
    "Address": "911 S Hazel Court",
    "Additional Notes": "Field Not Eligible for the\nNational Register – 2001",
    "Category": "Educational",
    "": "",
    "address_for_geocoding": "911 S Hazel Court Denver, CO",
    "Latitude": 39.6998022,
    "Longitude": -105.0285283
  },
  {
    "Site": "Centro Cultural",
    "Area": "Westside",
    "Address": "935 W. 11th Avenue",
    "Additional Notes": "",
    "Category": "Neighborhood",
    "": "",
    "address_for_geocoding": "935 W. 11th Avenue Denver, CO",
    "Latitude": 39.7338805,
    "Longitude": -104.9996536
  },
  {
    "Site": "Timeo’s Theater Bar",
    "Area": "Westside",
    "Address": "966 Santa Fe Drive",
    "Additional Notes": "",
    "Category": "Commercial",
    "": "",
    "address_for_geocoding": "966 Santa Fe Drive Denver, CO",
    "Latitude": 39.7317392,
    "Longitude": -104.9984225
  },
  {
    "Site": "Aztlán/Santa Fe Theater",
    "Area": "Westside",
    "Address": "974 Santa Fe Drive",
    "Additional Notes": "",
    "Category": "Commercial",
    "": "",
    "address_for_geocoding": "974 Santa Fe Drive Denver, CO",
    "Latitude": 39.7318662,
    "Longitude": -104.9983527
  },
  {
    "Site": "Aztlán/Santa Fe Theater",
    "Area": "Westside",
    "Address": "974 Santa Fe Drive",
    "Additional Notes": "",
    "Category": "Arts",
    "": "",
    "address_for_geocoding": "974 Santa Fe Drive Denver, CO",
    "Latitude": 39.7318662,
    "Longitude": -104.9983527
  },
  {
    "Site": "Sam Sandos Westside Family Health Center",
    "Area": "Westside",
    "Address": "990 Federal Boulevard (former location)",
    "Additional Notes": "Current location Former location (no longer exists)",
    "Category": "Neighborhood",
    "": "",
    "address_for_geocoding": "990 Federal Boulevard Denver, CO",
    "Latitude": 39.7326744,
    "Longitude": -105.0247846
  },
  {
    "Site": "Hector Flores Park",
    "Area": "Westside",
    "Address": "Galapago St. and W. 4th Ave.",
    "Additional Notes": "",
    "Category": "Political",
    "": "",
    "address_for_geocoding": "Galapago St. and W. 4th Ave. Denver, CO",
    "Latitude": 39.7225298,
    "Longitude": -104.9963698
  },
  {
    "Site": "Chicano Humanities & Arts Council (CHAC)",
    "Area": "Westside",
    "Address": "3401 Pecos Street 941 E. 17th Avenue 725 Santa Fe Drive 772-774 Santa Fe Drive 222 Santa Fe Drive",
    "Additional Notes": "Original Location Second Location (former location) (no longer exists) (former location) (former location) Designated Sites: National, State, or Local Landmark c",
    "Category": "Arts",
    "": "",
    "address_for_geocoding": "",
    "Latitude": "",
    "Longitude": ""
  },
  {
    "Site": "Chicano Humanities & Arts Council (CHAC)",
    "Area": "941 E. 17th Avenue 725 Santa Fe Drive 772-774 Santa Fe Drive 222 Santa Fe Drive",
    "Address": "",
    "Additional Notes": "Second Location (former location) (no longer exists) (former location) (former location)",
    "Category": "Neighborhood",
    "": "",
    "address_for_geocoding": "",
    "Latitude": "",
    "Longitude": ""
  },
  {
    "Site": "E scuela Tlatelolco Centro de Estudios",
    "Area": "Eastside, Northside, Northside",
    "Address": "1567 Downing Street (no longer exists)\nSouden Building, 4059\nTejon Street (no longer exists)\n2949 North Federal\nBoulevard (no longer exists)",
    "Additional Notes": "Original Location\nSecond Location\nOfficially Eligible for the\nNational Register– 2005\n(St. Dominic’s Elementary\nbuilding); Final Location",
    "Category": "Educational",
    "": "",
    "address_for_geocoding": "",
    "Latitude": "",
    "Longitude": ""
  },
  {
    "Site": "Escuela Tlatelolco Centro de Estudios",
    "Area": "Eastside Northside Northside",
    "Address": "1567 Downing Street (no longer exists) Souden Building, 4059 Tejon Street (no longer exists) St. Dominic’s Elementary building, 2949 North Federal Boulevard (no longer exists)",
    "Additional Notes": "Officially Eligible for the National Register– 2005 (Dominic’s Elementary building)",
    "Category": "Chicano Movement or Crusade for Justice",
    "": "",
    "address_for_geocoding": "",
    "Latitude": "",
    "Longitude": ""
  }
]