[
  {
    "state": "Alabama",
    "id": 1,
    "status": 0,
    "recreational": "",
    "medical": "",
    "ballot": "",
    "cbd": 2014,
    "hemp": "",
    "decriminalization": "",
    "mandatorysentencing": "Yes",
    "statelink": "http://www.thecannabist.co/tag/alabama/"
  },
  {
    "state": "Alaska",
    "id": 2,
    "status": 2,
    "recreational": "Voter approved in 2014",
    "medical": "Voter approval, 1998",
    "ballot": "",
    "cbd": "",
    "hemp": "",
    "decriminalization": "",
    "mandatorysentencing": "",
    "statelink": "http://www.thecannabist.co/tag/alaska/"
  },
  {
    "state": "Arizona",
    "id": 4,
    "status": 1,
    "recreational": "",
    "medical": "Voter approval, 2010",
    "ballot": "Recreational measure",
    "cbd": "",
    "hemp": "",
    "decriminalization": "",
    "mandatorysentencing": "",
    "statelink": "http://www.thecannabist.co/tag/arizona/"
  },
  {
    "state": "Arkansas",
    "id": 5,
    "status": 0,
    "recreational": "",
    "medical": "",
    "ballot": "Medical measures",
    "cbd": "",
    "hemp": "",
    "decriminalization": "",
    "mandatorysentencing": "Yes",
    "statelink": "http://www.thecannabist.co/tag/arkansas/"
  },
  {
    "state": "California",
    "id": 6,
    "status": 1,
    "recreational": "",
    "medical": "Voter approval, 1996",
    "ballot": "Recreational measure",
    "cbd": "",
    "hemp": "Yes",
    "decriminalization": "Yes",
    "mandatorysentencing": "",
    "statelink": "http://www.thecannabist.co/tag/california/"
  },
  {
    "state": "Colorado",
    "id": 8,
    "status": 2,
    "recreational": "Voter approved in 2012",
    "medical": "Voter approval, 2000",
    "ballot": "",
    "cbd": "",
    "hemp": "Yes",
    "decriminalization": "Yes",
    "mandatorysentencing": "",
    "statelink": "http://www.thecannabist.co/tag/colorado/"
  },
  {
    "state": "Connecticut",
    "id": 9,
    "status": 1,
    "recreational": "",
    "medical": "Legislation, 2012",
    "ballot": "",
    "cbd": "",
    "hemp": "Yes",
    "decriminalization": "Yes",
    "mandatorysentencing": "Yes",
    "statelink": "http://www.thecannabist.co/tag/connecticut/"
  },
  {
    "state": "Delaware",
    "id": 10,
    "status": 1,
    "recreational": "",
    "medical": "Legislation, 2011",
    "ballot": "",
    "cbd": "",
    "hemp": "Yes",
    "decriminalization": "Yes",
    "mandatorysentencing": "Yes",
    "statelink": "http://www.thecannabist.co/tag/delaware/"
  },
  {
    "state": "District of Columbia",
    "id": 11,
    "status": 2,
    "recreational": "Voter approval, 2014",
    "medical": "Voter approval, 1998",
    "ballot": "",
    "cbd": "",
    "hemp": "Yes",
    "decriminalization": "",
    "mandatorysentencing": "Yes",
    "statelink": "http://www.thecannabist.co/tag/washington-d-c/"
  },
  {
    "state": "Florida",
    "id": 12,
    "status": 0,
    "recreational": "",
    "medical": "",
    "ballot": "Medical measure",
    "cbd": 2014,
    "hemp": "",
    "decriminalization": "",
    "mandatorysentencing": "Yes",
    "statelink": "http://www.thecannabist.co/tag/florida/"
  },
  {
    "state": "Georgia",
    "id": 13,
    "status": 0,
    "recreational": "",
    "medical": "",
    "ballot": "",
    "cbd": 2015,
    "hemp": "",
    "decriminalization": "",
    "mandatorysentencing": "Yes",
    "statelink": "http://www.thecannabist.co/tag/georgia/"
  },
  {
    "state": "Hawaii",
    "id": 15,
    "status": 1,
    "recreational": "",
    "medical": "Legislation, 2000",
    "ballot": "",
    "cbd": "",
    "hemp": "Yes",
    "decriminalization": "",
    "mandatorysentencing": "",
    "statelink": "http://www.thecannabist.co/tag/hawaii/"
  },
  {
    "state": "Idaho",
    "id": 16,
    "status": 0,
    "recreational": "",
    "medical": "",
    "ballot": "",
    "cbd": "",
    "hemp": "",
    "decriminalization": "",
    "mandatorysentencing": "Yes",
    "statelink": "http://www.thecannabist.co/tag/idaho/"
  },
  {
    "state": "Illinois",
    "id": 17,
    "status": 1,
    "recreational": "",
    "medical": "Legislation, 2013",
    "ballot": "",
    "cbd": "",
    "hemp": "Yes",
    "decriminalization": "",
    "mandatorysentencing": "Yes",
    "statelink": "http://www.thecannabist.co/tag/illinois/"
  },
  {
    "state": "Indiana",
    "id": 18,
    "status": 0,
    "recreational": "",
    "medical": "",
    "ballot": "",
    "cbd": "",
    "hemp": "Yes",
    "decriminalization": "",
    "mandatorysentencing": "",
    "statelink": "http://www.thecannabist.co/tag/indiana/"
  },
  {
    "state": "Iowa",
    "id": 19,
    "status": 0,
    "recreational": "",
    "medical": "",
    "ballot": "",
    "cbd": 2014,
    "hemp": "",
    "decriminalization": "",
    "mandatorysentencing": "Yes",
    "statelink": "http://www.thecannabist.co/tag/iowa/"
  },
  {
    "state": "Kansas",
    "id": 20,
    "status": 0,
    "recreational": "",
    "medical": "",
    "ballot": "",
    "cbd": "",
    "hemp": "",
    "decriminalization": "",
    "mandatorysentencing": "Yes",
    "statelink": "http://www.thecannabist.co/tag/kansas/"
  },
  {
    "state": "Kentucky",
    "id": 21,
    "status": 0,
    "recreational": "",
    "medical": "",
    "ballot": "",
    "cbd": 2014,
    "hemp": "Yes",
    "decriminalization": "",
    "mandatorysentencing": "",
    "statelink": "http://www.thecannabist.co/tag/kentucky/"
  },
  {
    "state": "Louisiana",
    "id": 22,
    "status": 0,
    "recreational": "",
    "medical": "",
    "ballot": "",
    "cbd": 2015,
    "hemp": "",
    "decriminalization": "",
    "mandatorysentencing": "Yes",
    "statelink": "http://www.thecannabist.co/tag/louisiana/"
  },
  {
    "state": "Maine",
    "id": 23,
    "status": 1,
    "recreational": "",
    "medical": "Voter approved, 1999",
    "ballot": "Recreational measure",
    "cbd": "",
    "hemp": "Yes",
    "decriminalization": "Yes",
    "mandatorysentencing": "",
    "statelink": "http://www.thecannabist.co/tag/maine/"
  },
  {
    "state": "Maryland",
    "id": 24,
    "status": 1,
    "recreational": "",
    "medical": "Legislation, 2014",
    "ballot": "",
    "cbd": "",
    "hemp": "",
    "decriminalization": "Yes",
    "mandatorysentencing": "Yes",
    "statelink": "http://www.thecannabist.co/tag/maryland/"
  },
  {
    "state": "Massachusetts",
    "id": 25,
    "status": 1,
    "recreational": "",
    "medical": "Voter approved, 2012",
    "ballot": "Recreational measure",
    "cbd": "",
    "hemp": "",
    "decriminalization": "Yes",
    "mandatorysentencing": "Yes",
    "statelink": "http://www.thecannabist.co/tag/massachusetts/"
  },
  {
    "state": "Michigan",
    "id": 26,
    "status": 1,
    "recreational": "",
    "medical": "Voter approved, 2008",
    "ballot": "Proposed recreational measure failed to appear on ballot",
    "cbd": "",
    "hemp": "Yes",
    "decriminalization": "",
    "mandatorysentencing": "",
    "statelink": "http://www.thecannabist.co/tag/michigan/"
  },
  {
    "state": "Minnesota",
    "id": 27,
    "status": 1,
    "recreational": "",
    "medical": "Legislation, 2014",
    "ballot": "",
    "cbd": "",
    "hemp": "Yes",
    "decriminalization": "Yes",
    "mandatorysentencing": "",
    "statelink": "http://www.thecannabist.co/tag/minnesota/"
  },
  {
    "state": "Mississippi",
    "id": 28,
    "status": 0,
    "recreational": "",
    "medical": "",
    "ballot": "",
    "cbd": 2014,
    "hemp": "",
    "decriminalization": "Yes",
    "mandatorysentencing": "Yes",
    "statelink": "http://www.thecannabist.co/tag/mississippi/"
  },
  {
    "state": "Missouri",
    "id": 29,
    "status": 0,
    "recreational": "",
    "medical": "",
    "ballot": "Proposed medical measure awaiting approval for ballot",
    "cbd": 2014,
    "hemp": "Yes",
    "decriminalization": "",
    "mandatorysentencing": "Yes",
    "statelink": "http://www.thecannabist.co/tag/missouri/"
  },
  {
    "state": "Montana",
    "id": 30,
    "status": 1,
    "recreational": "",
    "medical": "Voter approved, 2004",
    "ballot": "Medical measure on ballot; Measures to rescind MMJ law and to allow recreational sales proposed",
    "cbd": "",
    "hemp": "Yes",
    "decriminalization": "",
    "mandatorysentencing": "Yes",
    "statelink": "http://www.thecannabist.co/tag/montana/"
  },
  {
    "state": "Nebraska",
    "id": 31,
    "status": 0,
    "recreational": "",
    "medical": "",
    "ballot": "",
    "cbd": "",
    "hemp": "Yes",
    "decriminalization": "Yes",
    "mandatorysentencing": "Yes",
    "statelink": "http://www.thecannabist.co/tag/nebraska/"
  },
  {
    "state": "Nevada",
    "id": 32,
    "status": 1,
    "recreational": "",
    "medical": "Voter approved, 2000",
    "ballot": "Recreational measure",
    "cbd": "",
    "hemp": "Yes",
    "decriminalization": "Yes",
    "mandatorysentencing": "Yes",
    "statelink": "http://www.thecannabist.co/tag/nevada/"
  },
  {
    "state": "New Hampshire",
    "id": 33,
    "status": 1,
    "recreational": "",
    "medical": "Legislation, 2013",
    "ballot": "",
    "cbd": "",
    "hemp": "",
    "decriminalization": "",
    "mandatorysentencing": "",
    "statelink": "http://www.thecannabist.co/tag/new-hampshire/"
  },
  {
    "state": "New Jersey",
    "id": 34,
    "status": 1,
    "recreational": "",
    "medical": "Legislation, 2009",
    "ballot": "",
    "cbd": "",
    "hemp": "",
    "decriminalization": "",
    "mandatorysentencing": "Yes",
    "statelink": "http://www.thecannabist.co/tag/new-jersey/"
  },
  {
    "state": "New Mexico",
    "id": 35,
    "status": 1,
    "recreational": "",
    "medical": "Legislation, 2007",
    "ballot": "",
    "cbd": "",
    "hemp": "",
    "decriminalization": "",
    "mandatorysentencing": "",
    "statelink": "http://www.thecannabist.co/tag/new-mexico/"
  },
  {
    "state": "New York",
    "id": 36,
    "status": 1,
    "recreational": "",
    "medical": "Legislation, 2014",
    "ballot": "",
    "cbd": "",
    "hemp": "Yes",
    "decriminalization": "Yes",
    "mandatorysentencing": "Yes",
    "statelink": "http://www.thecannabist.co/tag/new-york/"
  },
  {
    "state": "North Carolina",
    "id": 37,
    "status": 0,
    "recreational": "",
    "medical": "",
    "ballot": "",
    "cbd": 2014,
    "hemp": "Yes",
    "decriminalization": "Yes",
    "mandatorysentencing": "Yes",
    "statelink": "http://www.thecannabist.co/tag/north-carolina/"
  },
  {
    "state": "North Dakota",
    "id": 38,
    "status": 0,
    "recreational": "",
    "medical": "",
    "ballot": "Medical measure",
    "cbd": "",
    "hemp": "Yes",
    "decriminalization": "",
    "mandatorysentencing": "Yes",
    "statelink": "http://www.thecannabist.co/tag/north-dakota/"
  },
  {
    "state": "Ohio",
    "id": 39,
    "status": 1,
    "recreational": "",
    "medical": "Legislation, 2016",
    "ballot": "",
    "cbd": "",
    "hemp": "",
    "decriminalization": "Yes",
    "mandatorysentencing": "Yes",
    "statelink": "http://www.thecannabist.co/tag/ohio/"
  },
  {
    "state": "Oklahoma",
    "id": 40,
    "status": 0,
    "recreational": "",
    "medical": "",
    "ballot": "Proposed medical measure awaiting approval for ballot",
    "cbd": 2105,
    "hemp": "",
    "decriminalization": "",
    "mandatorysentencing": "Yes",
    "statelink": "http://www.thecannabist.co/tag/oklahoma/"
  },
  {
    "state": "Oregon",
    "id": 41,
    "status": 2,
    "recreational": "Voter approved, 2014",
    "medical": "Voter approved, 1998",
    "ballot": "",
    "cbd": "",
    "hemp": "Yes",
    "decriminalization": "",
    "mandatorysentencing": "",
    "statelink": "http://www.thecannabist.co/tag/oregon/"
  },
  {
    "state": "Pennsylvania",
    "id": 42,
    "status": 1,
    "recreational": "",
    "medical": "Legislation, 2016",
    "ballot": "",
    "cbd": "",
    "hemp": "",
    "decriminalization": "",
    "mandatorysentencing": "",
    "statelink": "http://www.thecannabist.co/tag/pennsylvania/"
  },
  {
    "state": "Rhode Island",
    "id": 44,
    "status": 1,
    "recreational": "",
    "medical": "Legislation, 2007",
    "ballot": "",
    "cbd": "",
    "hemp": "",
    "decriminalization": "Yes",
    "mandatorysentencing": "Yes",
    "statelink": "http://www.thecannabist.co/tag/rhode-island/"
  },
  {
    "state": "South Carolina",
    "id": 45,
    "status": 0,
    "recreational": "",
    "medical": "",
    "ballot": "",
    "cbd": 2014,
    "hemp": "Yes",
    "decriminalization": "",
    "mandatorysentencing": "Yes",
    "statelink": "http://www.thecannabist.co/tag/south-carolina/"
  },
  {
    "state": "South Dakota",
    "id": 46,
    "status": 0,
    "recreational": "",
    "medical": "",
    "ballot": "",
    "cbd": "",
    "hemp": "",
    "decriminalization": "",
    "mandatorysentencing": "Yes",
    "statelink": "http://www.thecannabist.co/tag/south-dakota/"
  },
  {
    "state": "Tennessee",
    "id": 47,
    "status": 0,
    "recreational": "",
    "medical": "",
    "ballot": "",
    "cbd": 2014,
    "hemp": "Yes",
    "decriminalization": "",
    "mandatorysentencing": "",
    "statelink": "http://www.thecannabist.co/tag/tennessee/"
  },
  {
    "state": "Texas",
    "id": 48,
    "status": 0,
    "recreational": "",
    "medical": "",
    "ballot": "",
    "cbd": 2015,
    "hemp": "",
    "decriminalization": "",
    "mandatorysentencing": "Yes",
    "statelink": "http://www.thecannabist.co/tag/texas/"
  },
  {
    "state": "Utah",
    "id": 49,
    "status": 0,
    "recreational": "",
    "medical": "",
    "ballot": "",
    "cbd": 2014,
    "hemp": "Yes",
    "decriminalization": "",
    "mandatorysentencing": "",
    "statelink": "http://www.thecannabist.co/tag/utah/"
  },
  {
    "state": "Vermont",
    "id": 50,
    "status": 1,
    "recreational": "",
    "medical": "Legislation, 2004",
    "ballot": "",
    "cbd": "",
    "hemp": "Yes",
    "decriminalization": "Yes",
    "mandatorysentencing": "",
    "statelink": "http://www.thecannabist.co/tag/vermont/"
  },
  {
    "state": "Virginia",
    "id": 51,
    "status": 0,
    "recreational": "",
    "medical": "",
    "ballot": "",
    "cbd": 2015,
    "hemp": "Yes",
    "decriminalization": "",
    "mandatorysentencing": "Yes",
    "statelink": "http://www.thecannabist.co/tag/virginia/"
  },
  {
    "state": "Washington",
    "id": 53,
    "status": 2,
    "recreational": "Voter approved, 2012",
    "medical": "Voter approved, 1998",
    "ballot": "",
    "cbd": "",
    "hemp": "",
    "decriminalization": "",
    "mandatorysentencing": "",
    "statelink": "http://www.thecannabist.co/tag/washington/"
  },
  {
    "state": "West Virginia",
    "id": 54,
    "status": 0,
    "recreational": "",
    "medical": "",
    "ballot": "",
    "cbd": "",
    "hemp": "Yes",
    "decriminalization": "",
    "mandatorysentencing": "Yes",
    "statelink": "http://www.thecannabist.co/tag/west-virginia/"
  },
  {
    "state": "Wisconsin",
    "id": 55,
    "status": 0,
    "recreational": "",
    "medical": "",
    "ballot": "",
    "cbd": 2013,
    "hemp": "",
    "decriminalization": "",
    "mandatorysentencing": "",
    "statelink": "http://www.thecannabist.co/tag/wisconsin/"
  },
  {
    "state": "Wyoming",
    "id": 56,
    "status": 0,
    "recreational": "",
    "medical": "",
    "ballot": "",
    "cbd": 2015,
    "hemp": "",
    "decriminalization": "",
    "mandatorysentencing": "",
    "statelink": "http://www.thecannabist.co/tag/wyoming/"
  }
]